endpoints:
  - displayName: "Docviewer1_delete" 
    url: "http://ER-ANW-enaio01.kbit.intern/osrenditioncache/app/api/document/38789160?_method=delete"
    auth_type: "BASIC"
    auth: "API_ENAIO_USER:API_ENAIO_PASSWORD"
    proxy: ""
    tag: "Docviewer"
    timeout: 5
    http_method: "GET"
    http_body: ""
    http_header: 
      Cache-Control: "no-cache"
